// Package zot contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package zot

// Config represents a structured data type
type Config struct {
	Version string `json:"version" yaml:"version"`
	DataDir string `json:"data_dir" yaml:"data_dir"`
	ConfigDir string `json:"config_dir" yaml:"config_dir"`
	Port int64 `json:"port" yaml:"port"`
	ContainerRuntime string `json:"container_runtime" yaml:"container_runtime"`
	StorageBackend *StorageConfig `json:"storage_backend,omitempty" yaml:"storage_backend,omitempty"`
	PullThroughCache bool `json:"pull_through_cache" yaml:"pull_through_cache"`
	Auth *AuthConfig `json:"auth,omitempty" yaml:"auth,omitempty"`
}

// StorageConfig represents a structured data type
type StorageConfig struct {
	Type string `json:"type" yaml:"type"`
	MountPath string `json:"mount_path" yaml:"mount_path"`
}

// AuthConfig represents a structured data type
type AuthConfig struct {
	Type string `json:"type" yaml:"type"`
	Config map[string]any `json:"config" yaml:",inline"`
}

