package dns

import (
	"fmt"
	"strings"
	"text/template"
)

// pdnsConfigTemplate is the PowerDNS configuration template.
const pdnsConfigTemplate = `# PowerDNS Authoritative Server Configuration
# Generated by Foundry

# API Configuration
api=yes
api-key={{.APIKey}}

# Backend Configuration
launch={{.Backend}}
{{.Backend}}-database={{.DataDir}}/pdns.db

# Web Server (for API)
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0

# DNS Listener Configuration
# Listen on localhost only - only the recursor should answer external queries
# The authoritative server answers queries from the recursor on port 5300
local-address=127.0.0.1
local-port=5300

# Lua Records (for split-horizon DNS)
enable-lua-records=yes

# Recursive Resolution
# Note: PowerDNS Authoritative doesn't do recursion directly
# Use recursor configuration or run pdns-recursor separately
# For now, we'll configure forwarders in the recursor config

# Logging
loglevel=4
log-dns-queries=no
log-dns-details=no

# Security
security-poll-suffix=
disable-syslog=no
guardian=yes

# Performance
cache-ttl=20
query-cache-ttl=20
negquery-cache-ttl=60
`

// recursorConfigTemplate is the PowerDNS Recursor configuration template (YAML format).
// PowerDNS Recursor 5.0+ requires YAML configuration with section headers.
const recursorConfigTemplate = `# PowerDNS Recursor Configuration (YAML)
# Generated by Foundry

# Incoming queries settings
incoming:
  listen:
    - 0.0.0.0:53

# Recursor settings
recursor:
  # Local zones - Forward to Authoritative server at 127.0.0.1:5300
  # These zones are managed by PowerDNS Auth and should be queried directly
{{- if .LocalZonesList}}
  forward_zones:
{{range $index, $zone := .LocalZonesList}}    - zone: {{$zone}}
      forwarders:
        - 127.0.0.1:5300
{{end}}
{{- end}}

  # Upstream forwarding - Forward all other queries to external DNS
  # The zone "." means forward ALL queries not matched by forward_zones above
  forward_zones_recurse:
    - zone: .
      forwarders:
{{range $index, $forwarder := .ForwardersList}}        - {{$forwarder}}
{{end}}

# Web service (API) settings
webservice:
  api_key: {{.APIKey}}
  address: 0.0.0.0
  port: 8082
  allow_from:
    - 0.0.0.0/0

# Performance settings
recordcache:
  max_entries: 1000000
  max_ttl: 86400
`

// GenerateAuthConfig generates the PowerDNS Authoritative Server configuration.
func GenerateAuthConfig(cfg *Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config cannot be nil")
	}

	if cfg.APIKey == "" {
		return "", fmt.Errorf("API key is required")
	}

	tmpl, err := template.New("pdns-auth").Parse(pdnsConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// GenerateRecursorConfig generates the PowerDNS Recursor configuration.
func GenerateRecursorConfig(cfg *Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config cannot be nil")
	}

	if cfg.APIKey == "" {
		return "", fmt.Errorf("API key is required")
	}

	if len(cfg.Forwarders) == 0 {
		return "", fmt.Errorf("at least one forwarder is required")
	}

	// Create template data with forwarders and local zones as lists for YAML format
	data := struct {
		APIKey         string
		ForwardersList []string
		LocalZonesList []string
	}{
		APIKey:         cfg.APIKey,
		ForwardersList: cfg.Forwarders,
		LocalZonesList: cfg.LocalZones,
	}

	tmpl, err := template.New("pdns-recursor").Parse(recursorConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}
