// Package openbaoinjector contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package openbaoinjector

// K8sAuthRole defines a Kubernetes auth role for a specific app
type K8sAuthRole struct {
	RoleName                string `json:"role_name" yaml:"role_name"`
	ServiceAccountName      string `json:"service_account_name" yaml:"service_account_name"`
	ServiceAccountNamespace string `json:"service_account_namespace" yaml:"service_account_namespace"`
	Policies                string `json:"policies" yaml:"policies"`
	TTL                     string `json:"ttl" yaml:"ttl"`
}

// Config represents a structured data type
type Config struct {
	Version           string        `json:"version" yaml:"version"`
	Namespace         string        `json:"namespace" yaml:"namespace"`
	ExternalVaultAddr string        `json:"external_vault_addr" yaml:"external_vault_addr"`
	ConfigureK8sAuth  bool          `json:"configure_k8s_auth" yaml:"configure_k8s_auth"`
	K8sAuthRoles      []K8sAuthRole `json:"k8s_auth_roles" yaml:"k8s_auth_roles"`
}
