// Package openbaoinjector contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package openbaoinjector

// Config represents a structured data type
type Config struct {
	Version          string `json:"version" yaml:"version"`
	Namespace        string `json:"namespace" yaml:"namespace"`
	ExternalVaultAddr string `json:"external_vault_addr" yaml:"external_vault_addr"`
}
