// Package config contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package config

// Manually added imports for cross-package type references
// TODO: Add go_imports support to csilgen parser for automatic imports
import (
	"github.com/catalystcommunity/foundry/v1/internal/setup"
	"github.com/catalystcommunity/foundry/v1/internal/host"
)

// NetworkConfig represents a structured data type
type NetworkConfig struct {
	Gateway string `json:"gateway" yaml:"gateway"`
	Netmask string `json:"netmask" yaml:"netmask"`
	DHCPRange *DHCPRange `json:"dhcp_range,omitempty" yaml:"dhcp_range,omitempty"`
	OpenBAOHosts []string `json:"openbao_hosts" yaml:"openbao_hosts"`
	DNSHosts []string `json:"dns_hosts" yaml:"dns_hosts"`
	ZotHosts []string `json:"zot_hosts" yaml:"zot_hosts"`
	TrueNASHosts []string `json:"truenas_hosts,omitempty" yaml:"truenas_hosts,omitempty"`
	K8sVIP string `json:"k8s_vip" yaml:"k8s_vip"`
}

// DHCPRange represents a structured data type
type DHCPRange struct {
	Start string `json:"start" yaml:"start"`
	End string `json:"end" yaml:"end"`
}

// DNSConfig represents a structured data type
type DNSConfig struct {
	InfrastructureZones []DNSZone `json:"infrastructure_zones" yaml:"infrastructure_zones"`
	KubernetesZones []DNSZone `json:"kubernetes_zones" yaml:"kubernetes_zones"`
	Forwarders []string `json:"forwarders" yaml:"forwarders"`
	Backend string `json:"backend" yaml:"backend"`
	APIKey string `json:"api_key" yaml:"api_key"`
}

// DNSZone represents a structured data type
type DNSZone struct {
	Name string `json:"name" yaml:"name"`
	Public bool `json:"public" yaml:"public"`
	PublicCNAME *string `json:"public_cname,omitempty" yaml:"public_cname,omitempty"`
}

// ClusterConfig represents a structured data type
type ClusterConfig struct {
	Name string `json:"name" yaml:"name"`
	Domain string `json:"domain" yaml:"domain"`
	K8sVIP *string `json:"k8s_vip,omitempty" yaml:"k8s_vip,omitempty"`
	Nodes []NodeConfig `json:"nodes" yaml:"nodes"`
}

// NodeConfig represents a structured data type
type NodeConfig struct {
	Hostname string `json:"hostname" yaml:"hostname"`
	Role string `json:"role" yaml:"role"`
}

// ComponentMap is a type alias
type ComponentMap map[string]ComponentConfig

// ComponentConfig represents a structured data type
type ComponentConfig struct {
	Version *string `json:"version,omitempty" yaml:"version,omitempty"`
	Hosts []string `json:"hosts,omitempty" yaml:"hosts,omitempty"`
	Config map[string]any `json:"config" yaml:",inline"`
}

// ObsConfig represents a structured data type
type ObsConfig struct {
	Prometheus *PrometheusConfig `json:"prometheus,omitempty" yaml:"prometheus,omitempty"`
	Loki *LokiConfig `json:"loki,omitempty" yaml:"loki,omitempty"`
	Grafana *GrafanaConfig `json:"grafana,omitempty" yaml:"grafana,omitempty"`
}

// PrometheusConfig represents a structured data type
type PrometheusConfig struct {
	Retention *string `json:"retention,omitempty" yaml:"retention,omitempty"`
}

// LokiConfig represents a structured data type
type LokiConfig struct {
	Retention *string `json:"retention,omitempty" yaml:"retention,omitempty"`
}

// GrafanaConfig represents a structured data type
type GrafanaConfig struct {
	AdminPassword *string `json:"admin_password,omitempty" yaml:"admin_password,omitempty"`
}

// StorageConfig represents a structured data type
type StorageConfig struct {
	TrueNAS *TrueNASConfig `json:"truenas,omitempty" yaml:"truenas,omitempty"`
}

// TrueNASConfig represents a structured data type
type TrueNASConfig struct {
	APIURL string `json:"api_url" yaml:"api_url"`
	APIKey string `json:"api_key" yaml:"api_key"`
}

// Config represents a structured data type
type Config struct {
	Network *NetworkConfig `json:"network,omitempty" yaml:"network,omitempty"`
	DNS *DNSConfig `json:"dns,omitempty" yaml:"dns,omitempty"`
	Cluster ClusterConfig `json:"cluster" yaml:"cluster"`
	Components ComponentMap `json:"components" yaml:"components"`
	Observability *ObsConfig `json:"observability,omitempty" yaml:"observability,omitempty"`
	Storage *StorageConfig `json:"storage,omitempty" yaml:"storage,omitempty"`
	Hosts []*host.Host `json:"hosts,omitempty" yaml:"hosts,omitempty"` // Manually added for host registry
	SetupState *setup.SetupState `json:"setup_state" yaml:"setup_state"`
}

