// Package ssh contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package ssh

// SSHKeyStorage represents a structured data type
type SSHKeyStorage struct {
	PrivateKey string `json:"private_key" yaml:"private_key"`
	PublicKey string `json:"public_key" yaml:"public_key"`
}

