// Package tailscale contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package tailscale

// Config represents a structured data type
type Config struct {
	OAuthClientID *string `json:"oauth_client_id,omitempty" yaml:"oauth_client_id,omitempty"`
	OAuthClientSecret *string `json:"oauth_client_secret,omitempty" yaml:"oauth_client_secret,omitempty"`
	OperatorImage *string `json:"operator_image,omitempty" yaml:"operator_image,omitempty"`
	AdvertiseRoutes []string `json:"advertise_routes,omitempty" yaml:"advertise_routes,omitempty"`
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

