// Package gatewaycontroller contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package gatewaycontroller

// Config represents a structured data type
type Config struct {
	Namespace        string         `json:"namespace" yaml:"namespace"`
	ImageRepository  string         `json:"image_repository" yaml:"image_repository"`
	ImageTag         string         `json:"image_tag" yaml:"image_tag"`
	GatewayName      string         `json:"gateway_name" yaml:"gateway_name"`
	GatewayNamespace string         `json:"gateway_namespace" yaml:"gateway_namespace"`
	EnvoyService     string         `json:"envoy_service" yaml:"envoy_service"`
	NetworkPolicy    string         `json:"network_policy" yaml:"network_policy"`
	Interval         string         `json:"interval" yaml:"interval"`
	ReplicaCount     uint64         `json:"replica_count" yaml:"replica_count"`
	Values           map[string]any `json:"values" yaml:",inline"`
}
