// Package k3s contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package k3s

// Config represents a structured data type
type Config struct {
	Version string `json:"version" yaml:"version"`
	VIP string `json:"vip" yaml:"vip"`
	Interface string `json:"interface" yaml:"interface"`
	ClusterToken string `json:"cluster_token" yaml:"cluster_token"`
	AgentToken string `json:"agent_token" yaml:"agent_token"`
	TLSSANs []string `json:"tls_sans" yaml:"tls_sans"`
	DisableComponents []string `json:"disable_components" yaml:"disable_components"`
	RegistryConfig string `json:"registry_config" yaml:"registry_config"`
	ClusterInit bool `json:"cluster_init" yaml:"cluster_init"`
	ServerURL string `json:"server_url" yaml:"server_url"`
	DNSServers []string `json:"dns_servers" yaml:"dns_servers"`
}

// RegistryConfig represents a structured data type
type RegistryConfig struct {
	Mirrors RegistryMirrorMap `json:"mirrors" yaml:"mirrors"`
	Configs RegistryAuthMap `json:"configs" yaml:"configs"`
}

// RegistryMirrorMap is a type alias
type RegistryMirrorMap map[string]RegistryMirror

// RegistryAuthMap is a type alias
type RegistryAuthMap map[string]RegistryAuth

// RegistryMirror represents a structured data type
type RegistryMirror struct {
	Endpoint []string `json:"endpoint" yaml:"endpoint"`
}

// RegistryAuth represents a structured data type
type RegistryAuth struct {
	Auth *RegistryAuthConfig `json:"auth,omitempty" yaml:"auth,omitempty"`
	Tls *RegistryTLSConfig `json:"tls,omitempty" yaml:"tls,omitempty"`
}

// RegistryAuthConfig represents a structured data type
type RegistryAuthConfig struct {
	Username *string `json:"username,omitempty" yaml:"username,omitempty"`
	Password *string `json:"password,omitempty" yaml:"password,omitempty"`
}

// RegistryTLSConfig represents a structured data type
type RegistryTLSConfig struct {
	InsecureSkipVerify *bool `json:"insecure_skip_verify,omitempty" yaml:"insecure_skip_verify,omitempty"`
}

// K3sClusterToken represents a structured data type
type K3sClusterToken struct {
	Token string `json:"token" yaml:"token"`
}

// K3sAgentToken represents a structured data type
type K3sAgentToken struct {
	Token string `json:"token" yaml:"token"`
}

